### ISSUE TITLE
FxTools_Linux Fqtools stat 没有输出ReadQ Q10 Q20

### ISSUE THREAD

**Issue by willright28** [BGI-shenzhen/FxTools#5]
你好

使用FxTools_Linux Fqtools stat时，没有输出ReadQ的Q10和Q20，以前多次使用未出现这样的情况。
代码：
FxTools_Linux Fqtools stat \
-i A_1.fq.gz A_2.fq.gz \
-o A.fq.stat

谢谢！

**Comment by hewm2008** [comment]
你好  说明你里面一条readQ Q10和Q20的都没有。 即测序质量非常好  均在readQ  均在Q20以上

**Comment by willright28** [comment]
好的，谢谢！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年1月18日(周二) 中午1:12
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [BGI-shenzhen/FxTools] FxTools_Linux Fqtools stat 没有输出ReadQ Q10 Q20 (Issue #5)




 
你好  说明你里面一条readQ Q10和Q20的都没有。 即测序质量非常好  均在readQ  均在Q20以上
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
