### ISSUE TITLE
warning:can't find the [convert] in your $PATH ; no png Figure Out

### ISSUE THREAD

**Issue by CristEin** [BGI-shenzhen/FxTools#6]
While running ./FxTools Fqtools fqcheck -i f1 f2 -o o1 o2 I get this warning message
`warning:can't find the [convert] in your $PATH ; no png Figure Out`
Is there any solution to fix this?

should install the apt-get install imagemagick?

Thanks in advance

**Comment by hewm2008** [comment]
A：
yes ,you can install  the covert first 
1) [convert](https://linux.die.net/man/1/convert) command is recommended to be pre-installed, although it is not required.  you can use the follow command to pre-install the  **convert**  command;
    `  sudo apt-get install ImageMagick`   or ` sudo yum  install  ImageMagick`

B:  By the way
The latest version of  fqcheck can be download here  [hewm2008/fqcheck](https://github.com/hewm2008/fqcheck)

**Comment by CristEin** [comment]
Thank you for giving your soul! Are you still at BGI?

**Comment by hewm2008** [comment]
Yes, I'm still here at BGI, but in a different department .
you can find my personal public repositories   here [github/hewm2008](https://github.com/hewm2008?tab=repositories)

**Comment by CristEin** [comment]
你好, 我的BGI 30855, 可以在钉钉上聊一下吗?  fqcheck的图片在安装ImageMagick后依然无法生成
